# RNN

In [1]:
import tensorflow as tf
import numpy as np
import pprint

LSTM(Long Short-Term Memory)<br>
GRU (Gated Recurrent Unit)<br>

# RNN 텐서플로우로 구현하기

In [15]:
n_inputs = 3
n_neurons = 9

X0 = tf.placeholder(tf.float32,[None,n_inputs])
X1 = tf.placeholder(tf.float32,[None,n_inputs])

Wx = tf.Variable(tf.random_normal([n_inputs,n_neurons],dtype=tf.float32))
Wy = tf.Variable(tf.random_normal([n_neurons,n_neurons],dtype=tf.float32))
b  = tf.Variable(tf.random_normal([1, n_neurons],dtype=tf.float32))

Y0 = tf.tanh(tf.matmul(X0,Wx)+b)
Y1 = tf.tanh(tf.matmul(Y0,Wy) + tf.matmul(X1,Wx)+b)


In [36]:
X0_batch = np.reshape(np.array([0,1,2,3,4,5,6,7,8,9,0,1]),[4,3])
X1_batch = np.reshape(np.array([9,8,7,0,0,0,6,5,4,3,2,1,]),[4,3])
print(X0_batch)
print(X1_batch)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    Y0_val, Y1_val = sess.run([Y0,Y1],feed_dict={X0:X0_batch,X1:X1_batch})

print(Y0_val)
print(Y1_val)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 0 1]]
[[9 8 7]
 [0 0 0]
 [6 5 4]
 [3 2 1]]
[[ 0.9018162  -0.7729402  -0.97352827 -0.97976667  0.9982137   0.99915004
  -0.9833705   0.8171874   0.4712433 ]
 [ 1.         -0.9999942  -0.9999997   0.33887997  1.          1.
  -0.99998957  0.53679377  0.99998534]
 [ 1.         -1.         -1.          0.99502856  1.          1.
  -1.          0.05094526  1.        ]
 [ 1.         -1.         -0.9999999   1.          0.999975    1.
  -0.96545845 -0.9999998   0.9983509 ]]
[[ 1.         -1.         -1.          1.          1.          1.
  -0.9999968  -0.9986629   1.        ]
 [ 0.946741   -0.96772534 -0.9989369  -0.9914771   0.6369976   0.9965579
   0.9486455  -0.7364628  -0.596579  ]
 [ 1.         -1.         -1.          0.9994358   1.          1.
  -0.99913067 -0.96827376  0.99999964]
 [ 0.9999999  -0.99998385 -0.9999956   0.9045925   0.99998695  0.99999994
  -0.13132203  0.12431943  0.77821594]]


In [16]:
batch_size = 100
h_size = 28
w_size = 28
c_size = 1
hidden_size = 100

In [23]:
x = np.arange(18).reshape(3, 6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [35]:
np.split(x,3,axis=0)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17]])]

In [40]:
def reset_graph(seed=42):
    tf.reset_default_graph()
    tf.set_random_seed(seed)
    np.random.seed(seed)

In [41]:
reset_graph()

X0 = tf.placeholder(tf.float32, [None, n_inputs])
X1 = tf.placeholder(tf.float32, [None, n_inputs])

basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)
output_seqs, states = tf.contrib.rnn.static_rnn(basic_cell, [X0, X1],
                                                dtype=tf.float32)
Y0, Y1 = output_seqs


In [49]:
init = tf.global_variables_initializer()

X0_batch = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 0, 1]])
X1_batch = np.array([[9, 8, 7], [0, 0, 0], [6, 5, 4], [3, 2, 1]])

with tf.Session() as sess:
    init.run()
    Y0_val, Y1_val = sess.run([Y0, Y1], feed_dict={X0: X0_batch, X1: X1_batch})
    print(sess.run(states,feed_dict={X0: X0_batch, X1: X1_batch}))

[[ 0.9971175  -0.8829431   0.9728114  -0.99983186 -0.9825391   0.9999999
  -0.99923575  0.9536618  -0.93503135]
 [ 0.72184837  0.852149   -0.3916083  -0.29725125 -0.5723039   0.81788385
   0.27009368  0.00758619 -0.91007894]
 [ 0.99314314  0.40417093  0.8735989  -0.99060535 -0.9561975   0.9999896
  -0.96979505  0.48968056 -0.9913083 ]
 [ 0.93675774 -0.45269105  0.22677751 -0.41911602 -0.8982261   0.9494737
  -0.94501865 -0.34868854 -0.78876   ]]


In [46]:
Y0_val

array([[-0.363332  , -0.22232606,  0.26016062, -0.84686536, -0.08355161,
         0.7731991 , -0.49710023,  0.47220647,  0.04955996],
       [ 0.3482791 , -0.7332364 ,  0.8356289 , -0.99613035, -0.6109184 ,
         0.9992797 , -0.9657425 ,  0.82141614, -0.3007551 ],
       [ 0.8032433 , -0.92820716,  0.97305304, -0.99990934, -0.8709556 ,
         0.9999979 , -0.9981933 ,  0.9477712 , -0.58517706],
       [ 0.97919905, -0.6567514 ,  0.9022057 ,  0.88642365,  0.77287304,
         0.9996306 , -0.99905014,  0.98280895, -0.99607754]],
      dtype=float32)

In [50]:
print(Y1_val)

[[ 0.9971175  -0.8829431   0.9728114  -0.99983186 -0.9825391   0.9999999
  -0.99923575  0.9536618  -0.93503135]
 [ 0.72184837  0.852149   -0.3916083  -0.29725125 -0.5723039   0.81788385
   0.27009368  0.00758619 -0.91007894]
 [ 0.99314314  0.40417093  0.8735989  -0.99060535 -0.9561975   0.9999896
  -0.96979505  0.48968056 -0.9913083 ]
 [ 0.93675774 -0.45269105  0.22677751 -0.41911602 -0.8982261   0.9494737
  -0.94501865 -0.34868854 -0.78876   ]]


In [79]:
n_steps = 2
n_inputs = 3
n_neurons = 5

reset_graph()

X = tf.placeholder(tf.float32, [None, n_steps, n_inputs])
basic_cell = tf.contrib.rnn.BasicRNNCell(num_units=n_neurons)

seq_length = tf.placeholder(tf.int32, [None])
outputs, states = tf.nn.dynamic_rnn(basic_cell, X, dtype=tf.float32,
                                    sequence_length=seq_length)

In [84]:
init = tf.global_variables_initializer()

X_batch = np.array([
        # 스텝 0     스텝 1
        [[0, 1, 2], [9, 8, 7]], # 샘플 1
        [[3, 4, 5], [0, 0, 0]], # 샘플 2 (0 벡터로 패딩)
        [[6, 7, 8], [6, 5, 4]], # 샘플 3
        [[9, 0, 1], [3, 2, 1]], # 샘플 4
    ])
seq_length_batch = np.array([2, 1, 2, 2])

with tf.Session() as sess:
    init.run()
    outputs_val, states_val = sess.run(
        [outputs, states], feed_dict={X: X_batch, seq_length: seq_length_batch})
    
print(outputs_val)
print(states_val)

[[[-0.9123188   0.16516446  0.5548655  -0.39159346  0.20846416]
  [-1.          0.9567258   0.9983168   0.99970174  0.9651857 ]]

 [[-0.9998612   0.6702291   0.9723653   0.6631046   0.74457586]
  [ 0.          0.          0.          0.          0.        ]]

 [[-0.99999976  0.8967997   0.9986295   0.9647514   0.93662   ]
  [-0.9999526   0.9681953   0.96002865  0.98706263  0.85459226]]

 [[-0.96435434  0.99501586 -0.36150697  0.9983378   0.999497  ]
  [-0.96135855  0.9568762   0.7132288   0.97729224 -0.0958299 ]]]
[[-1.          0.9567258   0.9983168   0.99970174  0.9651857 ]
 [-0.9998612   0.6702291   0.9723653   0.6631046   0.74457586]
 [-0.9999526   0.9681953   0.96002865  0.98706263  0.85459226]
 [-0.96135855  0.9568762   0.7132288   0.97729224 -0.0958299 ]]
